In [58]:
import pandas as pd
import datetime as dt

In [66]:
df = pd.read_csv("up00-tx-single-family_detached.csv")
df["date"] = pd.to_datetime(df.timestamp)
df["month"] = df.date.dt.month
df["time"] = df.date.dt.time
value_cols = ['ceiling fan', 'clothes dryer', 'clothes washer', 'cooling energy', 'cooling fans pumps', 'dishwasher',
       'freezer', 'heating energy', 'heating fans pumps', 'heating hp bkup',
       'heating hp bkup fa', 'hot water', 'lighting exterior',
       'lighting garage', 'lighting interior', 'mech vent',
       'permanent spa heat', 'permanent spa pump', 'plug loads', 'pool heater',
       'pool pump', 'pv', 'range oven', 'refrigerator','well pump','net_energy']

In [190]:
dfm_table = (dfm / 7049055.484)
dfm_table.loc['Total'] = dfm_table.sum()
dfm_table['total'] = dfm_table.sum(axis=1)
dfm_table = dfm_table.iloc[:, [0,1,2,3,4,25]]
dfm_table.applymap(lambda x: f"{x:.2f}")

,cooling energy,plug loads,heating energy,lighting interior,hot water,total
month,,,,,,
1,23.48,283.91,826.64,115.20,127.07,1617.23
2,53.71,257.60,423.17,101.05,112.72,1147.64
3,176.44,253.83,73.61,106.85,114.53,962.61
4,221.38,245.15,75.60,91.70,96.18,967.40
5,829.20,253.60,0.81,87.84,81.39,1619.61
6,1184.40,226.45,0.07,80.76,64.76,1980.32
7,1302.16,233.23,0.06,82.13,59.46,2124.98
8,1226.36,233.17,0.08,85.01,60.79,2040.71
9,749.98,226.50,0.86,89.55,68.61,1478.40
10,400.42,253.23,58.86,100.24,86.90,1170.80
11,90.74,244.72,294.36,107.22,101.41,1050.32
12,45.36,284.34,408.76,115.24,119.07,1191.79
Total,6303.62,2995.72,2162.89,1162.77,1092.87,17351.82

dfm = df.groupby("month")[value_cols].sum()

# Sort the columns based on the total
column_totals = dfm.div(dfm.sum(axis=1), axis=0).sum() * 100
sorted_columns = column_totals.sort_values(ascending=False).index
dfm = dfm[sorted_columns]

# Calculate the total percentage for each column
dfm_pct = (dfm.div(dfm.sum(axis=1), axis=0) * 100).applymap(lambda x: f"{x:.2f}%")

# Reorder the DataFrame columns based on sorted column names
dfm_pct = dfm_pct[sorted_columns]
dfm_pct.loc['Total'] = (dfm.sum(axis=0) / dfm.sum(axis=0).sum() * 100).apply(lambda x: f"{x:.2f}%")
dfm_pct

In [ ]:
dfm = df.groupby("month")[value_cols].sum()
dfm_pct = dfm.div(dfm.sum(axis=1), axis=0) * 100

# Add the 'Total %' row
dfm_pct.loc['Total %'] = dfm.sum(axis=0) / dfm.sum(axis=0).sum() * 100

# Transpose the DataFrame to sort by 'Total %' row
dfm_pct = dfm_pct.T

# Sort the DataFrame by 'Total %' row
dfm_pct = dfm_pct.sort_values(by='Total %', ascending=False)

# Transpose it back to the original format
dfm_pct = dfm_pct.T

# Format all the values as percentages
dfm_pct = dfm_pct.applymap(lambda x: f"{x:.2f}%")

dfm_pct

In [38]:
denom = df["net energy"].sum()

In [40]:
(dfs.sum() / denom * 100).sort_values(ascending=False)

cooling energy        36.328813
plug loads            17.264834
heating energy        12.465100
cooling fans pumps     7.591833
lighting interior      6.701254
hot water              6.298414
refrigerator           3.390958
clothes dryer          3.293905
range oven             1.409513
pool pump              1.403716
freezer                0.704932
lighting exterior      0.552432
dishwasher             0.498139
heating fans pumps     0.454713
permanent spa pump     0.409593
ceiling fan            0.391384
well pump              0.287170
permanent spa heat     0.206893
clothes washer         0.167860
lighting garage        0.140588
pool heater            0.139139
heating hp bkup        0.121770
mech vent              0.112367
heating hp bkup fa     0.003398
pv                    -0.337297
dtype: float64